### ISSUE TITLE
Absinthe Foam Width

### ISSUE THREAD

**Issue by dayofdoom** [cfbender/keyboards#10]
What is the recommended foam width for the Absinthe keyboard?

**Comment by cfbender** [comment]
Hey there @dayofdoom! That's a great point - I probably should've documented that somewhere. Since the plates are all 3mm thick, 2mm EVA foam works perfectly! You could go with slightly thicker if you want to compress it a bit, the cherry spec is 5mm between the bottom of where the switch sits and the pcb.
